---
- name: Setup DB server
  hosts: webservers
  become: yes
  tasks:
    - name: Install MySQL server
      apt:
        name: mariadb-server
        state: present
      become: true

    - name: Start & Enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install Python MySQL
      apt:
        name: python3-pymysql
        state: present
        

    - name: Create new database
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: devopsdb
        state: present

    - name: Create database user
      mysql_user:
       login_unix_socket: /var/run/mysqld/mysqld.sock
       name: devops
       password: 12345
       priv: '*.*:ALL'
       state: present
